;; @file    <data/articles.cljs>
;; @author  <wakaranakattari@gmail.com>
;; @info    <generated by scripts/gen-articles.mjs, do not edit>
;; @version <1.0>

;; @secstart->@secname <ns>
(ns bio-site.data.articles)
;; @secend->@secname   <ns>

;; @secstart->@secname <articles>
  ;; @funcinfo <articles manifest, embedded at build time>
(def articles
  [  {:slug "first-thoughts" :title "first thoughts" :category "ideas" :date "2026-08-06" :summary "this is where i will dump my ideas and thoughts."}])
;; @secend->@secname   <articles>
